config/routes.rb
Rails.application.routes.draw do
  get 'user/index'
  get 'admin/index'
  get 'home/admin'
  devise_for :users, :controllers => { :registrations => "users/registrations" } 
  root 'home#adminouser'
  get 'welcome/index'
  resources :schedules
  resources :staffs
  resources :roles
  resources :groups
  resources :coords
  resources :drops
  resources :schools
  #devise_for :users
  devise_for :views
  #root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coord.rb
class Coord < ApplicationRecord
  belongs_to :school
end

app/models/drop.rb
class Drop < ApplicationRecord
  belongs_to :school
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :school
  belongs_to :coord
  belongs_to :drop
end

app/models/list.rb
class List < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :group
  belongs_to :staff
end

app/models/school.rb
class School < ApplicationRecord
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :user
  belongs_to :school
  belongs_to :role
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :school
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!


  
    def adminouser
  
     if current_user.admin == true  
        redirect_to url_for(:controller => :admin, :action => :index)
        else
       redirect_to url_for(:controller => :welcome, :action => :index)
    end
  end

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: %i[ show edit update destroy ]

  # GET /staffs or /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1 or /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs or /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: "Staff was successfully created." }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1 or /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: "Staff was successfully updated." }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1 or /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: "Staff was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def staff_params
      params.require(:staff).permit(:user_id, :name, :id_empl, :school_id, :role_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coords_helper.rb
module CoordsHelper
end

app/helpers/drops_helper.rb
module DropsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/staffs/_form.html.erb
<%= form_with(model: staff) do |form| %>
  <% if staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
        <% staff.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :id_empl %>
    <%= form.text_field :id_empl %>
  </div>

  <div class="field">
    <%= form.label :school_id %>
    <%= form.text_field :school_id %>
  </div>

  <div class="field">
    <%= form.label :role_id %>
    <%= form.text_field :role_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<h1>Editing Staff</h1>

<%= render 'form', staff: @staff %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Staffs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Id empl</th>
      <th>School</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.user_id %></td>
        <td><%= staff.name %></td>
        <td><%= staff.id_empl %></td>
        <td><%= staff.school_id %></td>
        <td><%= staff.role_id %></td>
        <td><%= link_to 'Show', staff %></td>
        <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <td><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff', new_staff_path %>

app/views/staffs/new.html.erb
<h1>New Staff</h1>

<%= render 'form', staff: @staff %>

<%= link_to 'Back', staffs_path %>

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @staff.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @staff.name %>
</p>

<p>
  <strong>Id empl:</strong>
  <%= @staff.id_empl %>
</p>

<p>
  <strong>School:</strong>
  <%= @staff.school_id %>
</p>

<p>
  <strong>Role:</strong>
  <%= @staff.role_id %>
</p>

<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>