config/routes.rb
Rails.application.routes.draw do
  get 'user/index'
  get 'admin/index'
  get 'home/admin'
  devise_for :users, :controllers => { :registrations => "users/registrations" } 
  root 'home#adminouser'
  get 'welcome/index'
  resources :schedules
  resources :staffs
  resources :roles
  resources :groups
  resources :coords
  resources :drops
  resources :schools
  #devise_for :users
  devise_for :views
  #root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coord.rb
class Coord < ApplicationRecord
  belongs_to :school
end

app/models/drop.rb
class Drop < ApplicationRecord
  belongs_to :school
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :school
  belongs_to :coord
  belongs_to :drop
end

app/models/list.rb
class List < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :group
  belongs_to :staff
end

app/models/school.rb
class School < ApplicationRecord
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :user
  belongs_to :school
  belongs_to :role
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :school
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!


  
    def adminouser
  
     if current_user.admin == true  
        redirect_to url_for(:controller => :admin, :action => :index)
        else
       redirect_to url_for(:controller => :welcome, :action => :index)
    end
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: %i[ show edit update destroy ]

  # GET /schedules or /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1 or /schedules/1.json
    def show
    
      @salon = Schedule.find(params[:id])
        @stus = List.where(group_id:@salon.group_id, show:1)
           end
  
  

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules or /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: "Schedule was successfully created." }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1 or /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: "Schedule was successfully updated." }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1 or /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: "Schedule was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def schedule_params
      params.require(:schedule).permit(:group_id, :staff_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coords_helper.rb
module CoordsHelper
end

app/helpers/drops_helper.rb
module DropsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/schedules/_form.html.erb
<%= form_with(model: schedule) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
        <% schedule.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :group_id %>
    <%= form.text_field :group_id %>
  </div>

  <div class="field">
    <%= form.label :staff_id %>
    <%= form.text_field :staff_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schedules</h1>

<table>
  <thead>
    <tr>
      <th>Group</th>
      <th>Staff</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.group_id %></td>
        <td><%= schedule.staff_id %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<%= render "layouts/navbar2" %>

<style>

body
{
  padding-top: 70px;
}

table 
{
  border-collapse: collapse;
  border: 1px solid black;
} 

th,td 
{
  border: 1px solid black;
}

table.a 
{
  table-layout: auto;
  width: 180px;  
}

table.b 
{
  table-layout: fixed;
  width: 180px;  
}

table.c 
{
  table-layout: auto;
  width: 100%;  
}

table.d 
{
  table-layout: fixed;
  width: 100%;  
}
</style>
</head>
<body>
<h1>Alumnos <%= @salon.name %>  </h1>
<br>
<br>
<table class ="d">
  <thead>
    <tr>
      <th style="text-align:center">Nombre</th>
      <th style="text-align:center">DropOff</th>
      </tr>
  </thead>

  <tbody>
  <% @stus.each do |stu| %>
    <tr>
    <td style="text-align:left"><%= stu.name %> </td>
    <td style="text-align:center"><%= stu.drop %></td>
     </tr>
 <% end %>
</tbody>
</table>
<br>
<br>
<br>
<br>
<br>
<br>